export interface HelpFaqItem {
  id: number;
  category: 'sims' | 'payments' | 'privacy' | 'technical';
  question: string;
  answer: string;
}

export const HELP_FAQ_DATA: HelpFaqItem[] = [
  { id: 1, category: 'sims', question: '¿Son estas SIMs realmente físicas?', answer: 'Sí. A diferencia de los servicios VoIP convencionales, Telsim opera con infraestructura de puertos físicos reales. Esto garantiza que plataformas como WhatsApp, bancos o Google detecten el número como un dispositivo móvil legítimo, sin bloqueos ni restricciones de uso.' },
  { id: 2, category: 'sims', question: '¿Cómo recibo mis códigos SMS?', answer: 'Una vez activado tu número, cualquier SMS enviado a ese puerto llegará instantáneamente a tu sección de "Mensajes" en el panel de Telsim. También puedes configurar notificaciones en tiempo real por Telegram para recibirlos sin abrir la app.' },
  { id: 3, category: 'sims', question: '¿Puedo renovar mi número después del mes?', answer: 'Sí. Puedes activar la renovación automática desde los ajustes de tu número para mantener el puerto indefinidamente. Si no activas la renovación, el número se libera automáticamente al vencer el periodo.' },
  { id: 4, category: 'sims', question: '¿En qué países están disponibles los números?', answer: 'Actualmente ofrecemos números de múltiples países incluyendo Estados Unidos, Reino Unido, Canadá, España, México y más. La disponibilidad de cada región se muestra en tiempo real al seleccionar tu plan.' },
  { id: 5, category: 'sims', question: '¿Puedo usar el número para llamadas de voz?', answer: 'Nuestros puertos físicos están optimizados para la recepción de SMS y códigos de verificación. Las llamadas de voz no están disponibles en los planes actuales, ya que el servicio se centra en la integridad del canal SMS.' },
  { id: 6, category: 'payments', question: '¿Qué métodos de pago aceptan?', answer: 'Aceptamos todas las tarjetas de crédito y débito principales (Visa, Mastercard, Amex), así como pagos por transferencia bancaria en algunos planes. Los pagos son procesados de forma segura por Stripe con encriptación SSL.' },
  { id: 7, category: 'payments', question: '¿Puedo cancelar mi suscripción en cualquier momento?', answer: 'Sí, puedes cancelar tu suscripción desde el panel de Facturación en cualquier momento. El acceso continúa hasta el fin del periodo pagado. No cobramos penalizaciones por cancelación anticipada.' },
  { id: 8, category: 'payments', question: '¿Ofrecen reembolsos?', answer: 'Sí, ofrecemos una garantía de satisfacción con reembolso del 100% dentro de los primeros 7 días desde la compra, sujeta a revisión técnica. Aplica solo a la primera compra o primera línea de la cuenta, y únicamente cuando el servicio no cumple lo prometido y hubo un uso legítimo y razonable. No aplica en casos de abuso, fraude, consumo sustancial del servicio, múltiples cuentas o uso intensivo solo para validaciones puntuales. La solicitud debe hacerse por ticket dentro del plazo y se evalúa con logs técnicos antes de aprobarse.' },
  { id: 9, category: 'payments', question: '¿Qué diferencia hay entre los planes?', answer: 'Los planes difieren en el número de puertos activos simultáneos, la velocidad de activación y el acceso a números premium de ciertos países. El plan Pro incluye acceso a API, renovación automática y notificaciones por Telegram.' },
  { id: 10, category: 'privacy', question: '¿Mis datos están seguros?', answer: 'Sí. Telsim aplica encriptación de extremo a extremo en todas las comunicaciones. No compartimos datos personales con terceros. Cumplimos con las normativas GDPR y de protección de datos locales. Puedes revisar nuestra política de privacidad completa en Ajustes → Términos y Privacidad.' },
  { id: 11, category: 'privacy', question: '¿Qué pasa si pierdo el acceso a mi cuenta?', answer: 'Contamos con protocolos de recuperación de identidad. Si tienes activada la Verificación de Identidad en Ajustes, podrás recuperar tu saldo y números vinculados. Sin verificación, el proceso es más lento y requiere validación manual por soporte.' },
  { id: 12, category: 'privacy', question: '¿Puedo activar autenticación de dos factores?', answer: 'Sí. Desde Ajustes → Seguridad puedes activar 2FA con cualquier aplicación TOTP (Google Authenticator, Authy, etc.). Es altamente recomendable para proteger el acceso a tus puertos activos.' },
  { id: 13, category: 'technical', question: '¿Tienen API para automatizar la recepción de SMS?', answer: 'Sí. El plan Pro incluye acceso completo a nuestra API REST. Puedes consultar la documentación desde el panel principal → Guía API. La API permite listar números, leer SMS y configurar webhooks para recibir mensajes en tiempo real en tu sistema.' },
  { id: 14, category: 'technical', question: '¿Qué son los webhooks y cómo los configuro?', answer: 'Los webhooks envían automáticamente cada SMS recibido a una URL de tu servidor al instante. Ve a tu número → Configuración → Webhooks. Puedes probar el webhook, ver los logs de entrega y manejar reintentos en caso de fallo.' },
  { id: 15, category: 'technical', question: '¿Por qué no llega un SMS esperado?', answer: 'Las causas más comunes son: (1) La plataforma bloqueó el número por uso previo — prueba activar otro número. (2) El SMS fue enviado pero hay retraso del operador — espera hasta 2 minutos. (3) La plataforma requiere un número de un país específico. Si el problema persiste, crea un ticket con el número afectado y la plataforma de origen.' },
  { id: 16, category: 'technical', question: '¿Cómo configuro las notificaciones por Telegram?', answer: 'Ve a tu perfil → Telegram. Sigue los pasos para conectar tu bot de Telegram personal. Una vez configurado, recibirás cada SMS directamente en tu chat de Telegram con el número, remitente y contenido completo.' },
];
